version: '2.1'
services:
  dbc-backend:
    build: 
      context: ./DBCDumpHost
      dockerfile: DBCDumpHost/Dockerfile
    volumes:
    - ./DBCDumpHost/caches:/caches
    - ./DBCDumpHost.config.json:/app/config.json
    - ./WoWDBDefs/definitions:/definitions
    restart: unless-stopped
  casc-backend:
    build: 
      context: ./CASCToolHost
      dockerfile: CASCToolHost/Dockerfile
    depends_on: 
      - mysql
    volumes:
    - ./CASCToolHost.config.json:/app/config.json
    - ./tpr:/var/www/wow.tools/tpr
    restart: unless-stopped
  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wowtools
  site:
    build: 
      context: ./www
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./www:/var/www/wow.tools
      - ./tpr:/var/www/wow.tools/tpr
  nginx:
    image: nginx:1.19
    restart: unless-stopped
    depends_on:
      - casc-backend
      - dbc-backend
      - site
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/wow.tools
      - ./wow.tools.conf:/etc/nginx/conf.d/default.conf:ro
      - ./fastcgi_params.conf:/etc/nginx/fastcgi_params:ro